# Generated by Django 5.1.4 on 2025-01-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_aiservice_url_aiservice_path_aiservice_tagid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('uploaded_file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/', verbose_name='파일')),
                ('origin_filename', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('attach_filename', models.CharField(max_length=255, verbose_name='첨부 파일명')),
                ('file_path', models.CharField(max_length=255, verbose_name='파일 경로')),
                ('attach_ext', models.CharField(max_length=10, verbose_name='파일 확장자')),
                ('file_size', models.BigIntegerField(verbose_name='파일 크기')),
                ('doc_no', models.BigIntegerField(verbose_name='문서 번호')),
            ],
            options={
                'verbose_name': '업로드된 파일',
                'verbose_name_plural': '업로드된 파일들',
                'db_table': 'tb_uploaded_file',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VectorFile',
            fields=[
                ('vector_file_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_no', models.BigIntegerField(verbose_name='문서 번호')),
                ('vector_file_path', models.CharField(max_length=255, verbose_name='벡터 파일 경로')),
            ],
            options={
                'verbose_name': '벡터 파일',
                'verbose_name_plural': '벡터 파일들',
                'db_table': 'tb_vector_file',
            },
        ),
    ]
